language: python

python:
  - 2.7

# Use container-based infrastructure
sudo: false

env:
  - DISABLE_NOTIFIER=true

install:
  - npm install gulp --global
  - npm install gulp --save-dev
  - npm install

  - pip install "pip>=1.5.6"
  - pip install requests pyOpenSSL ndg-httpsclient pyasn1
  - pip install docutils
  - pip install -r submission-form-scripts/requirements.txt

script:
  - gulp clean
  - gulp styles
  - gulp scripts

  # Python unit tests
  - python submission-form-scripts/test_botsheeter.py
  # Error and style-checker
  - flake8 submission-form-scripts/*.py
